version: '3.9'
services:
  auth_app:
    container_name: auth_app
    image: proyecto-web-auth:1.0
    build: .
    ports:
      - "8081:8080"
    environment:
      - DATABASE_URL=jdbc:mysql://auth_db:3306/musiclist
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=secret
    depends_on:
        - auth_db
  auth_db:
    container_name: auth_db
    image: mysql:8.1.0
    restart: always
    volumes:
      - authvolume:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=musiclist
volumes:
  authvolume:
